#!/bin/sh

# Easier navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ~='cd ~'
alias d='cd ~/Desktop'
alias dl='cd ~/Downloads'
alias cfg="cd ~/.config"
alias zcfg='cd ~/.config/zsh'

# School
alias uw='ssh -Y r28aggar@linux.student.cs.uwaterloo.ca'
alias cpl='g++ --std=c++17 -o'
alias leak='valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all'

# Dot aliases
alias dot='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
alias daa='dot add -u'
alias ds='dot status'
alias dcm='dot commit -m'
alias dcam='dot add -u && dot commit -m'

# Shortcuts 
alias tls="tmux ls"
alias rgr="ranger"
alias tks="tmux kill-server"
alias npmu='npm uninstall'
alias npmi='npm install'
alias rnm='rm -rf node_modules/ && npm install'
alias ls='lsd'
alias la='ls -al'
alias zrc='nvim ~/.config/zsh/.zshrc'
alias gbls='brew list && npm list -g --depth 0'
alias al='nvim ~/.config/zsh/aliases'
alias xcode='open -a Xcode'

alias fstart='cd ~/Desktop/Faire/backend/docker/compose/dependencies/ && brew services start mysql@5.7 && docker-compose up -d && cd ../../../'
# alias end='brew services stop mysql@5.7 && docker stop $(docker ps -a -q)'

alias cat='bat'

# git
alias g='git'
alias gaa='git add .'
alias gb='git branch'
alias gcam='git add --all && git commit -m'
alias gcm='git commit -m'
alias gc='git checkout'
alias gcb='git checkout -b'
alias gcf='git config --list'
alias gcl='git clone'
alias gclean='git clean -fd'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gd='git diff | bat'
alias gdel='git branch -D'
alias gf='git fetch'
alias gpl='git pull origin'
alias gp='git push origin'
alias gsup='git branch --set-upstream-to=origin/$(git_current_branch)'
alias glg='git log'
alias gm='git merge'
alias gpristine='git reset --hard && git clean -dfx'
alias gr='git remote'
alias gra='git remote add origin'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbm='git rebase master'
alias grbs='git rebase --skip'
alias grset='git remote set-url'
alias gs='git status'
alias gst='git stash'
alias undo='git reset --soft HEAD~1'

alias src='source ~/.config/zsh/.zshrc' 
alias paths='echo -e ${PATH//:/\\n}'

# colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

alias rmd='rm -rf'

# update Homebrew, npm, and their installed packages
alias update='brew update; brew upgrade; brew cleanup; npm install npm -g; npm update -g;'

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash='rm -rfv ~/.Trash'

# Show/hide hidden files in Finder
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
